import pygame
#TAMA;O DE LA PANTALLA
WIDTH = 800         # ANCHO
HEIGHT = 600       #ALTO
SIZE_SCREEN = (WIDTH,HEIGHT) #PANTALLA

#CORDENADA DE PANTALLA
CENTER = (WIDTH // 2, HEIGHT // 2)
MIDDLE_BOTTOM = (WIDTH // 2, HEIGHT)
DISPLAY_LEFT = 0
DISPLAY_RIGHT = WIDTH
DISPLAY_CENTER_UP = (WIDTH // 2, 0)
DISPLAY_BOTTOM =  HEIGHT
DISPLAY_CUSTOM = (WIDTH // 2, HEIGHT - 100)

#ICONO
SIZE_ICON = (32, 32)
ORIGIN = (0, 0)

#NAVE
SIZE_SHIP = (70, 70)

#DONA
DONA_SIZE = (60, 60)

#SCORE POS
SCORE_POS = (10,10)

#COLORES
ROJO = (255,0,0)
VERDE = (0,255,0)
AZUL = (0,0,255)
NEGRO = (0,0,0)
BLANCO = (255,255,255)
CUSTOM = (157,123,236)
AMARILLO = (255,255,0)


#RELOJ
clock = pygame.time.Clock()

#FPS
FPS = 60

#SPEED
SPEED_HERO = 3
DONA_SPEED = 3

#ASTEROIDE
SPEED_ASTEROIDE = 5
MAX_ASTEROIDES = 10
SIZE_ASTEROIDE = (30, 30)

#LASER
SIZE_LASER = (5,30)
COLOR_LASER = (191, 4, 4)
SPEED_LASER = 5

#FIREBALL
SPEED_FIREBALL = 5
SIZE_FIREBALL = (50,50)


#HERO
SIZE_HERO = (50,70)

#ENEMY
MAX_ENEMY = 2
SIZE_ENEMY = (60, 60)
SPEED_ENEMY = 1

#CORAZON
SIZE_HEART = (10,10)


#Item de speed up
SIZE_ITEM = (50, 50)

#speed up shoot
SPEED_UP_ITEM = 2

#item de te hace peque;o
ITEM_SIZE_REDUCE = 5

#que aumente los enemigos